# Generated by Django 3.0.7 on 2020-09-19 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_things'),
    ]

    operations = [
        migrations.AlterField(
            model_name='things',
            name='age',
            field=models.IntegerField(),
        ),
    ]
