# Generated by Django 3.0.7 on 2020-09-20 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_project2_tag_videoinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='videoinfo',
            name='tag',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
