# Generated by Django 3.0.7 on 2020-09-20 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200920_1221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoInfo',
            new_name='VideoInfo2',
        ),
    ]
