# Generated by Django 3.0.7 on 2020-10-03 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20200920_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='project2',
            name='not_objects',
            field=models.BooleanField(default=False),
        ),
    ]
