# Generated by Django 3.0.7 on 2020-10-04 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_project2_not_objects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datapoints',
            name='project',
        ),
        migrations.RemoveField(
            model_name='project',
            name='customer',
        ),
        migrations.DeleteModel(
            name='Things',
        ),
        migrations.DeleteModel(
            name='DataPoints',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
